## Sunny S.H | Division B | Roll No: 17
## Practical-**2.1**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy - Indexing & Slicing
Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.


In [ ]:
import numpy as np

In [ ]:
sunny_list = [1,2,3]
sunny_list

[1, 2, 3]

In [ ]:
np.array(sunny_list)

array([1, 2, 3])

In [ ]:
sun_matrix = [[1,2,3],[4,5,6],[7,8,9]]
sun_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(sun_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

### arange
###### The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros & Ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#5x5 zero matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Linspace
##### Return Evenly spaced numbers over a specified interval

In [ ]:
# 3 elements between 0 to 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Eye
#### Create an Identity Matrix

In [ ]:
#4x4 Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
##### Numpy has lots of ways to create random number arrays

## Rand
##### Create an array of the given shape and populate it with random samples from uniform distribution over [0,1)

In [ ]:
# 2 random numbers
np.random.rand(2)

array([0.46812671, 0.39606056])

In [ ]:
np.random.rand(5,5)

array([[0.19313348, 0.60840786, 0.20740596, 0.80524391, 0.62716184],
       [0.18511262, 0.36981247, 0.19772373, 0.13584539, 0.31753298],
       [0.69107914, 0.27127714, 0.7166042 , 0.41367679, 0.77880513],
       [0.54694604, 0.14016165, 0.5588182 , 0.67634813, 0.25473906],
       [0.79884702, 0.11273722, 0.38307998, 0.92954901, 0.69747648]])

### Randn

In [ ]:
np.random.randn(2)

array([-1.2851217 ,  0.65589777])

In [ ]:
np.random.randn(5,5)

array([[ 1.40629359, -0.59228619,  0.05789866, -1.63610767,  0.07572424],
       [-0.3608951 ,  0.29151754, -0.75897314, -1.41275088, -1.47047096],
       [ 1.87685452,  0.31186254, -0.34941884, -0.82736067,  1.68331821],
       [-0.78676287,  0.56237506, -0.08669821,  1.24461482,  0.58584166],
       [-0.61266747, -0.37258435, -0.00623907,  0.78423523, -2.10290633]])

### randint
##### Return random integers from low (inclusive) to high (exclusive)

In [ ]:
np.random.randint(1,100)

45

In [ ]:
#generate 10 random numbers
np.random.randint(1,100,10)

array([79, 97, 24, 28, 52, 66,  7, 10, 36, 19])

### Array Attributes & Methods

In [ ]:
sunny_arr1 = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
sunny_arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([25, 11,  8, 30,  4, 17, 16, 25, 19, 25])

### Reshape
##### Returns an array containing the same data with a new shape

In [ ]:
sunny_arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

In [ ]:
ranarr

array([25, 11,  8, 30,  4, 17, 16, 25, 19, 25])

In [ ]:
ranarr.max() #returns maximum from array

30

In [ ]:
ranarr.min()  #returns minimum from array

4

In [ ]:
ranarr.argmax() #returns index of max element

3

In [ ]:
ranarr.argmin() #returns index of min element.

4

### shape
##### shape is an attribute that arrays have dimensions

In [ ]:
sunny_arr1.shape

(25,)

In [ ]:
sunny_arr1.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
sunny_arr1.reshape(1,25).shape

(1, 25)

In [ ]:
sunny_arr1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
sunny_arr1.reshape(25,1).shape

(25, 1)

### dtype
##### Find data type of the object in an array

In [ ]:
sunny_arr1.dtype

dtype('int64')

## Numpy Operations
### 1. Arithemetic

In [ ]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr2 * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr2 / arr2

<ipython-input-40-a5d8023d8ed7>:1: RuntimeWarning: invalid value encountered in true_divide
  arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/ arr2

<ipython-input-41-39a5363a91ec>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/ arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr2 ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array Functions

In [ ]:
# Square roots
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# Calculating Exponential (e^x)
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr2)

9

In [ ]:
np.min(arr2)

0

In [ ]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
#create sample array
sunny_arr = np.arange(0,5) # 5 is exclusive
sunny_arr

array([0, 1, 2, 3, 4])

# Bracket Indexing & Selection

In [ ]:
#Get a value at an index
sunny_arr[3]

3

In [ ]:
#Get values in a range
sunny_arr[1:3] #1 - Inclusive & 3 Exclusive

array([1, 2])

In [ ]:
#Get values in a range
sunny_arr[0:4]

array([0, 1, 2, 3])

## Broadcasting

In [ ]:
#Setting a value with index range
sunny_arr[0:2] = 500
sunny_arr

array([500, 500,   2,   3,   4])

In [ ]:
#rest array
sunny_arr = np.arange(0,15)
sunny_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#slices
slice_of_arr = sunny_arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
#change of slice
# replacing every element with 55 in array
slice_of_arr[:] = 55
slice_of_arr

array([55, 55, 55, 55, 55])

In [ ]:
sunny_arr

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#copy array
arr_copy = sunny_arr.copy()
arr_copy

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing a 2D array

In [ ]:
arr_2d = np.array(([2,4,6],[8,10,12],[14,16,18]))
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#indexing row
arr_2d[1]

array([ 8, 10, 12])

In [ ]:
#Format is arr_2d[row][col] or arr_2d[row,col]
arr_2d[1][1]

10

In [ ]:
#Get individual element value
arr_2d[1,0]

8

In [ ]:
#2d array slicing
#shape (2,2) from top right corner
arr_2d[:1,2:]

array([[6]])

In [ ]:
#shape bottom row
arr_2d[2]

array([14, 16, 18])

In [ ]:
#shape bottom row
arr_2d[1,:]

array([ 8, 10, 12])

## Fancy Indexing

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#length of array
sunny_arr_length = arr2d.shape
sunny_arr_length

(10, 10)

In [ ]:
sunny_arr_length = arr2d.shape[1]
sunny_arr_length

10

In [ ]:
#Set up array
for i in range(sunny_arr_length):
  arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

###  Fancy Indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
sunny_bool_arr = arr > 6
sunny_bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
arr[sunny_bool_arr]

array([ 7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x=2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

___

___



```
# This is formatted as code
```

# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
arr = np.ones(10) * 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.randint(0,2)

1

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.normal(0,1,25)

array([ 0.22011643, -0.77125339, -0.94475657, -0.09710206,  0.77615701,
        1.35405061,  0.4395297 ,  0.34424379, -0.5687737 , -1.33257635,
       -0.06187294,  1.51911434, -1.77623077, -1.06840646,  0.7133467 ,
        1.4787096 ,  0.73801311, -1.37353695,  1.83916568, -0.50956551,
        0.47639384,  0.89897351,  0.79743606,  0.19577437, -1.46326308])

#### Create the following matrix:

In [ ]:
np.linspace(0.01, 1, num=100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[2:5, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[4,]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

### **Conclusions**:
#### We have Successfully implemented various Numpy Operations in this practical Successfully.